# Generated by Django 5.2.7 on 2026-01-11 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicaciones', '0002_tarea_fecha_creacion_tarea_fecha_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='alumnos_participantes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rol': 'ALUMNO'}, related_name='tareas_participante', to=settings.AUTH_USER_MODEL),
        ),
    ]
